services:
  db:
    build: ./docker/database/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: estacionapi-database
    ports: ["${DB_PORT}:5432"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file: [.env]
    volumes: [postgres_data:/var/lib/postgresql/data]

  api:
    build: ./api
    container_name: estacionapi-api
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env]

volumes:
  postgres_data:
