spring:
  application:
    name: EstacionApi

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}

  jackson:
    default-property-inclusion: non_null

  jpa:
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
