CREATE TABLE marcas (
   id SMALLINT GENERATED ALWAYS AS IDENTITY,
   nome VARCHAR(32) UNIQUE NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE modelos (
   id SMALLINT GENERATED ALWAYS AS IDENTITY,
   nome VARCHAR(32) NOT NULL,
   marca_id SMALLINT NOT NULL,
   PRIMARY KEY (id),
   CONSTRAINT uq_modelo_marca UNIQUE(nome, marca_id),
   FOREIGN KEY (marca_id) REFERENCES marcas(id) ON DELETE CASCADE
);

CREATE TABLE clientes (
   id INTEGER GENERATED ALWAYS AS IDENTITY,
   nome VARCHAR(150) NOT NULL,
   telefone VARCHAR(15) NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE carros (
   id INTEGER GENERATED ALWAYS AS IDENTITY,
   placa CHAR(7) UNIQUE NOT NULL,
   cor SMALLINT NOT NULL,
   modelo_id SMALLINT NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(modelo_id) REFERENCES modelos(id)
);

CREATE TABLE precos (
   id SMALLINT GENERATED ALWAYS AS IDENTITY,
   preco DECIMAL(10, 2) NOT NULL CHECK(preco >= 0),
   nome VARCHAR(100) NOT NULL,
   descricao TEXT,
   PRIMARY KEY(id)
);

CREATE TABLE entradas (
   carro_id INTEGER NOT NULL,
   cliente_id INTEGER NOT NULL,
   entrada TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   preco_base DECIMAL(10, 2) NOT NULL,
   preco_id SMALLINT,
   saida TIMESTAMPTZ CHECK(saida IS NULL OR saida >= entrada),
   PRIMARY KEY(carro_id, entrada),
   FOREIGN KEY(carro_id) REFERENCES carros(id) ON DELETE CASCADE,
   FOREIGN KEY(cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
   FOREIGN KEY(preco_id) REFERENCES precos(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_entrada_aberta
ON entradas(carro_id)
WHERE saida IS NULL;
