INSERT INTO precos (preco, nome, descricao) VALUES 
(100.00, 'Carros grandes', 'Estacionamento de carros grandes'),
(150.00, 'Carros médios', 'Estacionamento de carros médios'),
(200.00, 'Carros pequenos', 'Estacionamento de carros pequenos');

INSERT INTO marcas (nome) VALUES
('Ford'),
('Audi'),
('Mercedes'),
('Toyota'),
('Honda'),
('Chevrolet'),
('Volkswagen'),
('BMW'),
('Hyundai'),
('Nissan'),
('Kia'),
('Peugeot'),
('Renault'),
('Fiat'),
('Jeep'),
('Volvo'),
('Porsche'),
('Mitsubishi'),
('Subaru'),
('Lexus');

INSERT INTO modelos (nome, marca_id) VALUES
('Ka', 1),
('Fiesta', 1),
('Focus', 1),
('A3', 2),
('A4', 2),
('Q5', 2),
('Classe C', 3),
('GLA 200', 3),
('Corolla', 4),
('Hilux', 4),
('Yaris', 4),
('Civic', 5),
('HR-V', 5),
('Onix', 6),
('Tracker', 6),
('Gol', 7),
('Jetta', 7),
('T-Cross', 7),
('320i', 8),
('X1', 8),
('HB20', 9),
('Creta', 9),
('Sentra', 10),
('Kicks', 10),
('Sportage', 11),
('Cerato', 11),
('208', 12),
('3008', 12),
('Sandero', 13),
('Duster', 13),
('Uno', 14),
('Argo', 14),
('Toro', 14),
('Compass', 15),
('Renegade', 15),
('XC60', 16),
('911 Carrera', 17),
('Cayenne', 17),
('L200 Triton', 18),
('Impreza', 19),
('UX 250h', 20);
